"""
SGI (Semantic Grounding Index) Service: Measures how grounded the model's output is.

This module calculates the angular distance ratio between generated tokens and:
1. Context (source text) - smaller angle = well grounded
2. Question (input) - smaller angle = just repeating the question

SGI Score = θ(response, question) / (θ(response, context) + ε)
- SGI > 1.0: Grounded (response is closer to context than question)
- SGI < 1.0: Semantic laziness (response is closer to question than context)
"""

import torch
import torch.nn.functional as F
from typing import List, Tuple
from transformer_lens import HookedTransformer


def split_text_for_sgi(full_text: str, split_at_last_sentence: bool = False) -> Tuple[str, str]:
    """
    Automatically split input text into context and question portions. It splits either by
    the last sentence if it exists or the last 20% of the text.
    
    Args:
        full_text: The complete input text
        split_at_last_sentence: If True, split at last sentence boundary.
                               If False, split at last 20% of text.
    
    Returns:
        Tuple of (context, question)
        
    Examples:
        >>> text = "Paris is the capital. What about London?"
        >>> split_text_for_sgi(text)
        ("Paris is the capital.", "What about London?")
    """
    full_text = full_text.strip()
    
    if not full_text:
        return "", ""
    
    if split_at_last_sentence:
        # Try to split at last sentence boundary (., !, ?)
        sentence_endings = ['.', '!', '?']
        last_split_pos = -1
        
        for i in range(len(full_text) - 1, -1, -1):
            if full_text[i] in sentence_endings:
                # Make sure it's not the very end (we want incomplete text as question)
                if i < len(full_text) - 1:
                    last_split_pos = i + 1
                    break
        
        if last_split_pos > 0:
            context = full_text[:last_split_pos].strip()
            question = full_text[last_split_pos:].strip()
            return context, question
    
    # Fallback: split at last 20% of text (or minimum 10 chars for the question)
    split_point = len(full_text) - max(len(full_text) // 5, 10)
    split_point = max(min(split_point, len(full_text) - 1), 0)
    
    # Try to split at a space to avoid breaking words
    while split_point > 0 and full_text[split_point] not in [' ', '\n', '\t']:
        split_point -= 1
    
    if split_point <= 0:
        # Very short text, use first half as context
        split_point = len(full_text) // 2
    
    context = full_text[:split_point].strip()
    question = full_text[split_point:].strip()
    
    return context, question


class SGICalculator:
    """Computes Semantic Grounding Index for generated tokens."""
    
    def __init__(self, model: HookedTransformer):
        self.model = model
    
    def calculate_sgi(
        self,
        context: str,
        question: str,
        generated_tokens: List[str]
    ) -> List[Tuple[str, float, float, float]]:
        """
        Calculate SGI scores for each generated token using angular distance ratio.
        
        Args:
            context: Source text/context
            question: User's input question
            generated_tokens: List of tokens generated by the model
        
        Returns:
            List of tuples: (token, context_angular_distance, question_angular_distance, sgi_score)
        """
        # get embeddings for context and question
        context_embedding = self._get_text_embedding(context)
        question_embedding = self._get_text_embedding(question)
        
        results = []
        for token in generated_tokens:
            # get embedding for this token
            token_embedding = self._get_token_embedding(token)
            
            # calculate angular distances
            theta_rc = self._angular_distance(token_embedding, context_embedding)
            theta_rq = self._angular_distance(token_embedding, question_embedding)
            
            # calculate SGI ratio: θ(r,q) / (θ(r,c) + ε)
            epsilon = 1e-8
            sgi_score = theta_rq / (theta_rc + epsilon)
            
            results.append((token, theta_rc, theta_rq, sgi_score))
        
        return results
    
    def calculate_sgi_auto_split(
        self,
        full_text: str,
        generated_tokens: List[str],
        split_at_sentence: bool = False
    ) -> Tuple[str, str, List[Tuple[str, float, float, float]]]:
        """
        Calculate SGI with automatic text splitting using angular distance ratio.
        
        Automatically splits the input text into context and question,
        then calculates SGI scores.
        
        Args:
            full_text: Complete input text to split
            generated_tokens: List of tokens generated by the model
            split_at_sentence: If True, split at last sentence. Otherwise split at 80/20.
        
        Returns:
            Tuple of (context, question, sgi_results)
            
        Example:
            >>> text = "Paris is the capital of France. What is the capital?"
            >>> calculator.calculate_sgi_auto_split(text, ["Paris"])
            ("Paris is the capital of France.", "What is the capital?", [...])
        """
        context, question = split_text_for_sgi(full_text, split_at_sentence)
        results = self.calculate_sgi(context, question, generated_tokens)
        return context, question, results
    
    def _get_text_embedding(self, text: str) -> torch.Tensor:
        """Get averaged embedding for a text span."""
        tokens = self.model.to_tokens(text)
        
        with torch.no_grad():
            # get embeddings from the model's embed layer
            embeddings = self.model.embed(tokens)  # [batch, seq_len, d_model]
            # average across sequence length
            avg_embedding = embeddings.mean(dim=1)  # [batch, d_model]
        
        return avg_embedding.squeeze(0)  # [d_model]
    
    def _get_token_embedding(self, token: str) -> torch.Tensor:
        """Get embedding for a single token."""
        # tokenize and get embedding
        token_ids = self.model.to_tokens(token)
        
        with torch.no_grad():
            embeddings = self.model.embed(token_ids)
            # take the last token's embedding (in case of multi-token)
            token_embedding = embeddings[0, -1, :]  # [d_model]
        
        return token_embedding
    
    def _cosine_similarity(self, vec1: torch.Tensor, vec2: torch.Tensor) -> float:
        """Calculate cosine similarity between two vectors (deprecated - use angular distance)."""
        similarity = F.cosine_similarity(vec1.unsqueeze(0), vec2.unsqueeze(0))
        return similarity.item()
    
    def _angular_distance(self, vec1: torch.Tensor, vec2: torch.Tensor) -> float:
        """
        Calculate angular distance between two vectors on the unit hypersphere.
        
        Angular distance is the geodesic distance (arc length) between two points
        on the unit sphere, measured as the angle θ between them.
        
        Args:
            vec1: First vector
            vec2: Second vector
            
        Returns:
            Angular distance in radians (0 to π)
        """
        # Ensure vectors are L2-normalized (unit length)
        vec1 = F.normalize(vec1, p=2, dim=-1)
        vec2 = F.normalize(vec2, p=2, dim=-1)
        
        # Calculate dot product (cosine similarity since they are unit vectors)
        dot_product = torch.dot(vec1, vec2)
        
        # Clip for numerical stability to prevent NaNs in arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)
        
        # Return the geodesic distance (arc length)
        return torch.acos(dot_product).item()
